gradmatch:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    selection_lr: [0.01]
    selection_batch: [16]
    lam: [0.5] # recommended by Grad-Match paper
    random_seed: [0, 1, 42]

gradmatch_acf:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    fraction: [0.25]
    selection_lr: [0.01]
    selection_batch: [16]
    lam: [0.5]
    random_seed: [0, 1, 42]

tsds:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    random_seed: [0, 1, 42]

no_filter:
    fraction: [1]
    random_seed: [0, 1, 42]

random_filter:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    random_seed: [0, 1, 42]

match_dist:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    random_seed: [0, 1, 42]

clip_score:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    random_seed: [0, 1, 42]

zcore:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    n_sample: [500, 5000, 10000]
    redund_nn: [100, 1000, 10000]
    sample_dim: [2, 4, 6]
    random_seed: [0, 1, 42]

glister:
    fraction: [0.05, 0.10, 0.25, 0.5, 0.75, 0.9]
    selection_lr: [0.01]
    selection_batch: [16]
    eta: [0.1]
    random_seed: [0, 1, 42]
