gradmatch:
    # fraction: [0.5, 0.75, 0.9]
    # selection_lr: [0.01]
    # selection_batch: [4]

    # fraction: [0.25, 0.5, 0.75, 0.9]
    # selection_lr: [0.01, 0.001, 0.0001]
    # selection_batch: [4, 16]

    # fraction: [0.25]
    # selection_lr: [0.01]
    # selection_batch: [4]

    # best GradMatch hyperparameters
    fraction: [0.25, 0.5]
    selection_lr: [0.0001]
    selection_batch: [16]

# TODO: update tsds with actual params we want to sweep over
tsds:
    fraction: [0.25, 0.5, 0.75, 0.9]
    alpha: [0, 0.5, 1.0]

no_filter:
    fraction: [1]

random_filter:
    fraction: [0.25, 0.5, 0.75, 0.9]

match_dist:
    fraction: [0.25, 0.5, 0.75, 0.9]

zcore:
    fraction: [0.25, 0.5, 0.75, 0.9]
    n_sample: [500, 5000, 10000]
    redund_nn: [100, 1000, 10000]
    sample_dim: [2, 4, 6]