GeoDE:
    csv_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/GeoDE/splits/'
    img_root_path: "/data/vision/beery/scratch/neha/task-datacomp/all_datasets/GeoDE/geode/images/"
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "classification"
    FILEPATHS: 
        test1: 'test1.csv'
        test2: 'test2.csv'
        test3: 'test3.csv'
        test4: 'test4.csv'
        train: 'train.csv'
        val1: 'val1.csv'
        val2: 'val2.csv'
        val3: 'val3.csv'
        val4: 'val4.csv'
AutoArborist:
    csv_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/AutoArborist/splits/'
    img_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/AutoArborist/'
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "classification"
    FILEPATHS: 
        test1: 'testCalgary.csv'
        test2: 'testLosAngeles.csv'
        test3: 'testSurrey.csv'
        test4: 'testWashingtonDc.csv'
        train: 'train.csv'
        val1: 'valCalgary.csv'
        val2: 'valLosAngeles.csv'
        val3: 'valSurrey.csv'
        val4: 'valWashingtonDc.csv'
iWildCam:
    csv_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/iWildCam/redone_splits/'
    img_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/iWildCam/iwildcam_v2.0/train/'
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "classification"
    FILEPATHS: 
        test1: 'test1_id.csv'
        test2: 'test1_ood.csv'
        test3: 'test3_id.csv'
        test4: 'test3_ood.csv'
        train: 'train.csv'
        val1: 'val1_id.csv'
        val2: 'val1_ood.csv'
        val3: 'val3_id.csv'
        val4: 'val3_ood.csv'
iWildCamCropped:
    csv_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/iWildCam/new_splits/'
    img_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/iWildCam/iwildcam_v2.0/crops/'
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "classification"
    FILEPATHS: 
        test1: 'test1_id.csv'
        test2: 'test1_ood.csv'
        test3: 'test3_id.csv'
        test4: 'test3_ood.csv'
        train: 'train.csv'
        val1: 'val1_id.csv'
        val2: 'val1_ood.csv'
        val3: 'val3_id.csv'
        val4: 'val3_ood.csv'
SelfDrivingCar:
    csv_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/SelfDrivingCar/splits/'
    img_root_path: '/data/vision/beery/scratch/neha/task-datacomp/all_datasets/SelfDrivingCar/images/'
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: 'regression'
    FILEPATHS: 
        test1: 'test0.csv'
        test2: 'test1.csv'
        test3: 'test2.csv'
        test4: 'test3.csv'
        train: 'train.csv'
        val1: 'val0.csv'
        val2: 'val1.csv'
        val3: 'val2.csv'
        val4: 'val3.csv'
FMoW:
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "classification"
FishDetection:
    csv_root_path: "/data/vision/beery/scratch/neha/task-datacomp/all_datasets/FishDetection/splits/"
    img_root_path: '/data/vision/beery/scratch/fish_detection/fish_detection_ss/fish-detection-ss-yolo-640p/'
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "detection"
    FILEPATHS: 
        test1: 'viame-test-1.csv'
        test2: 'viame-test-2.csv'
        test3: 'viame-test-3.csv'
        test4: 'viame-test-4.csv'
        train: 'viame-train.csv'
        val: 'viame-val.csv'
        val1: 'viame-query-1.csv'
        val2: 'viame-query-2.csv'
        val3: 'viame-query-3.csv'
        val4: 'viame-query-4.csv'
ReID:
    csv_root_path: "/data/vision/beery/scratch/neha/task-datacomp/all_datasets/ReID/splits/"
    img_root_path: '/archive/vision/beery/animal_reid/datasets/wildlife-datasets/'
    task_list: ["test1", "test2", "test3", "test4"]
    training_task: "reid"
    FILEPATHS: 
        test1: 'test1.csv'
        test2: 'test2.csv'
        test3: 'test3.csv'
        test4: 'test4.csv'
        train: 'train.csv'
        val1: 'val1.csv'
        val2: 'val2.csv'
        val3: 'val3.csv'
        val4: 'val4.csv'


